import MODULE from './module'

export default {
  FETCH_USER: `@${MODULE}/FETCH_USER_REQUEST`,
  FETCH_USER_SUCCESS: `@${MODULE}/FETCH_USER_SUCCESS`,
  FETCH_USER_ERROR: `@${MODULE}/FETCH_USER_ERROR`,
  ADD_SONG_TO_LIBRARY: `@${MODULE}/ADD_SONG_TO_LIBRARY_REQUEST`,
  ADD_SONG_TO_LIBRARY_SUCCESS: `@${MODULE}/ADD_SONG_TO_LIBRARY_SUCCESS`,
  ADD_SONG_TO_LIBRARY_ERROR: `@${MODULE}/ADD_SONG_TO_LIBRARY_ERROR`,
}
