import MODULE from './module'

export default {
  SEARCH_ALBUNS: `@${MODULE}/SEARCH_ALBUNS`,
  SEARCH_ALBUNS_SUCESS: `@${MODULE}/SEARCH_ALBUNS_SUCESS`,
  SEARCH_ALBUNS_ERROR: `@${MODULE}/SEARCH_ALBUNS_ERROR`,
}
