import MODULE from './module'

export default {
  SEARCH_ALBUMS: `@${MODULE}/SEARCH_ALBUMS`,
  SEARCH_ALBUMS_SUCCESS: `@${MODULE}/SEARCH_ALBUMS_SUCCESS`,
  SEARCH_ALBUMS_ERROR: `@${MODULE}/SEARCH_ALBUMS_ERROR`,
}
