export default {
  albums: {
    href:
      'https://api.spotify.com/v1/search?query=RIHANNA&type=album&offset=0&limit=20',
    items: [
      {
        album_type: 'single',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/6rFkZxhheU9l1nODgZm4SP',
            },
            href: 'https://api.spotify.com/v1/artists/6rFkZxhheU9l1nODgZm4SP',
            id: '6rFkZxhheU9l1nODgZm4SP',
            name: 'Junior Lord',
            type: 'artist',
            uri: 'spotify:artist:6rFkZxhheU9l1nODgZm4SP',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/2Yv3YuHlHmeSnMYdF5hhzS',
        },
        href: 'https://api.spotify.com/v1/albums/2Yv3YuHlHmeSnMYdF5hhzS',
        id: '2Yv3YuHlHmeSnMYdF5hhzS',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/ab67616d0000b273c2744f6a4677f1677b3eca12',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/ab67616d00001e02c2744f6a4677f1677b3eca12',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/ab67616d00004851c2744f6a4677f1677b3eca12',
            width: 64,
          },
        ],
        name: 'Rihanna',
        release_date: '2019-06-21',
        release_date_precision: 'day',
        total_tracks: 1,
        type: 'album',
        uri: 'spotify:album:2Yv3YuHlHmeSnMYdF5hhzS',
      },
      {
        album_type: 'album',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5pKCCKE2ajJHZ9KAiaK11H',
            },
            href: 'https://api.spotify.com/v1/artists/5pKCCKE2ajJHZ9KAiaK11H',
            id: '5pKCCKE2ajJHZ9KAiaK11H',
            name: 'Rihanna',
            type: 'artist',
            uri: 'spotify:artist:5pKCCKE2ajJHZ9KAiaK11H',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/4UlGauD7ROb3YbVOFMgW5u',
        },
        href: 'https://api.spotify.com/v1/albums/4UlGauD7ROb3YbVOFMgW5u',
        id: '4UlGauD7ROb3YbVOFMgW5u',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/ab67616d0000b27333c6b920eabcf4c00d7a1093',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/ab67616d00001e0233c6b920eabcf4c00d7a1093',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/ab67616d0000485133c6b920eabcf4c00d7a1093',
            width: 64,
          },
        ],
        name: 'ANTI (Deluxe)',
        release_date: '2016-01-28',
        release_date_precision: 'day',
        total_tracks: 16,
        type: 'album',
        uri: 'spotify:album:4UlGauD7ROb3YbVOFMgW5u',
      },
      {
        album_type: 'album',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5pKCCKE2ajJHZ9KAiaK11H',
            },
            href: 'https://api.spotify.com/v1/artists/5pKCCKE2ajJHZ9KAiaK11H',
            id: '5pKCCKE2ajJHZ9KAiaK11H',
            name: 'Rihanna',
            type: 'artist',
            uri: 'spotify:artist:5pKCCKE2ajJHZ9KAiaK11H',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/3JSWZWeTHF4HDGt5Eozdy7',
        },
        href: 'https://api.spotify.com/v1/albums/3JSWZWeTHF4HDGt5Eozdy7',
        id: '3JSWZWeTHF4HDGt5Eozdy7',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/ab67616d0000b273f9f27162ab1ed45b8d7a7e98',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/ab67616d00001e02f9f27162ab1ed45b8d7a7e98',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/ab67616d00004851f9f27162ab1ed45b8d7a7e98',
            width: 64,
          },
        ],
        name: 'Good Girl Gone Bad: Reloaded',
        release_date: '2008-06-02',
        release_date_precision: 'day',
        total_tracks: 15,
        type: 'album',
        uri: 'spotify:album:3JSWZWeTHF4HDGt5Eozdy7',
      },
      {
        album_type: 'album',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5pKCCKE2ajJHZ9KAiaK11H',
            },
            href: 'https://api.spotify.com/v1/artists/5pKCCKE2ajJHZ9KAiaK11H',
            id: '5pKCCKE2ajJHZ9KAiaK11H',
            name: 'Rihanna',
            type: 'artist',
            uri: 'spotify:artist:5pKCCKE2ajJHZ9KAiaK11H',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/7vN82vd1Vq44fjlhjfvHJp',
        },
        href: 'https://api.spotify.com/v1/albums/7vN82vd1Vq44fjlhjfvHJp',
        id: '7vN82vd1Vq44fjlhjfvHJp',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/ab67616d0000b273be99e0ef9d3e6a1b55d94e78',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/ab67616d00001e02be99e0ef9d3e6a1b55d94e78',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/ab67616d00004851be99e0ef9d3e6a1b55d94e78',
            width: 64,
          },
        ],
        name: 'Loud',
        release_date: '2010-11-16',
        release_date_precision: 'day',
        total_tracks: 12,
        type: 'album',
        uri: 'spotify:album:7vN82vd1Vq44fjlhjfvHJp',
      },
      {
        album_type: 'album',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5pKCCKE2ajJHZ9KAiaK11H',
            },
            href: 'https://api.spotify.com/v1/artists/5pKCCKE2ajJHZ9KAiaK11H',
            id: '5pKCCKE2ajJHZ9KAiaK11H',
            name: 'Rihanna',
            type: 'artist',
            uri: 'spotify:artist:5pKCCKE2ajJHZ9KAiaK11H',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/5pLlGJrxuQO3jMoQe1XxZY',
        },
        href: 'https://api.spotify.com/v1/albums/5pLlGJrxuQO3jMoQe1XxZY',
        id: '5pLlGJrxuQO3jMoQe1XxZY',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/ab67616d0000b2736dee21d6cd1823e4d6231d37',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/ab67616d00001e026dee21d6cd1823e4d6231d37',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/ab67616d000048516dee21d6cd1823e4d6231d37',
            width: 64,
          },
        ],
        name: 'Unapologetic (Deluxe)',
        release_date: '2012-12-11',
        release_date_precision: 'day',
        total_tracks: 17,
        type: 'album',
        uri: 'spotify:album:5pLlGJrxuQO3jMoQe1XxZY',
      },
      {
        album_type: 'album',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5pKCCKE2ajJHZ9KAiaK11H',
            },
            href: 'https://api.spotify.com/v1/artists/5pKCCKE2ajJHZ9KAiaK11H',
            id: '5pKCCKE2ajJHZ9KAiaK11H',
            name: 'Rihanna',
            type: 'artist',
            uri: 'spotify:artist:5pKCCKE2ajJHZ9KAiaK11H',
          },
        ],
        available_markets: [
          'AD',
          'AR',
          'AU',
          'BG',
          'BO',
          'BR',
          'CA',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DO',
          'EC',
          'EE',
          'ES',
          'FI',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IL',
          'IN',
          'IS',
          'JP',
          'LI',
          'LT',
          'LV',
          'MC',
          'MT',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'PA',
          'PE',
          'PH',
          'PL',
          'PT',
          'PY',
          'RO',
          'SG',
          'SK',
          'SV',
          'TH',
          'TR',
          'TW',
          'US',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/2g1EakEaW7fPTZC6vBmBCn',
        },
        href: 'https://api.spotify.com/v1/albums/2g1EakEaW7fPTZC6vBmBCn',
        id: '2g1EakEaW7fPTZC6vBmBCn',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/ab67616d0000b273bef074de9ca825bddaeb9f46',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/ab67616d00001e02bef074de9ca825bddaeb9f46',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/ab67616d00004851bef074de9ca825bddaeb9f46',
            width: 64,
          },
        ],
        name: 'Talk That Talk',
        release_date: '2011-11-18',
        release_date_precision: 'day',
        total_tracks: 11,
        type: 'album',
        uri: 'spotify:album:2g1EakEaW7fPTZC6vBmBCn',
      },
      {
        album_type: 'album',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5pKCCKE2ajJHZ9KAiaK11H',
            },
            href: 'https://api.spotify.com/v1/artists/5pKCCKE2ajJHZ9KAiaK11H',
            id: '5pKCCKE2ajJHZ9KAiaK11H',
            name: 'Rihanna',
            type: 'artist',
            uri: 'spotify:artist:5pKCCKE2ajJHZ9KAiaK11H',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/7uGmyYwDFJbSc1xs4hkEs2',
        },
        href: 'https://api.spotify.com/v1/albums/7uGmyYwDFJbSc1xs4hkEs2',
        id: '7uGmyYwDFJbSc1xs4hkEs2',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/ab67616d0000b273ab647295c0c97446c1f1a3b5',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/ab67616d00001e02ab647295c0c97446c1f1a3b5',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/ab67616d00004851ab647295c0c97446c1f1a3b5',
            width: 64,
          },
        ],
        name: 'Rated R',
        release_date: '2009-11-20',
        release_date_precision: 'day',
        total_tracks: 13,
        type: 'album',
        uri: 'spotify:album:7uGmyYwDFJbSc1xs4hkEs2',
      },
      {
        album_type: 'single',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5pKCCKE2ajJHZ9KAiaK11H',
            },
            href: 'https://api.spotify.com/v1/artists/5pKCCKE2ajJHZ9KAiaK11H',
            id: '5pKCCKE2ajJHZ9KAiaK11H',
            name: 'Rihanna',
            type: 'artist',
            uri: 'spotify:artist:5pKCCKE2ajJHZ9KAiaK11H',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'IE',
          'IL',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/4S8F794ucXJcAtycwOZgR9',
        },
        href: 'https://api.spotify.com/v1/albums/4S8F794ucXJcAtycwOZgR9',
        id: '4S8F794ucXJcAtycwOZgR9',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/ab67616d0000b273c137319751a89295f921cce8',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/ab67616d00001e02c137319751a89295f921cce8',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/ab67616d00004851c137319751a89295f921cce8',
            width: 64,
          },
        ],
        name: 'Bitch Better Have My Money',
        release_date: '2015-03-26',
        release_date_precision: 'day',
        total_tracks: 1,
        type: 'album',
        uri: 'spotify:album:4S8F794ucXJcAtycwOZgR9',
      },
      {
        album_type: 'single',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5pKCCKE2ajJHZ9KAiaK11H',
            },
            href: 'https://api.spotify.com/v1/artists/5pKCCKE2ajJHZ9KAiaK11H',
            id: '5pKCCKE2ajJHZ9KAiaK11H',
            name: 'Rihanna',
            type: 'artist',
            uri: 'spotify:artist:5pKCCKE2ajJHZ9KAiaK11H',
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5K4W6rqBFWDnAN6FQUkS6x',
            },
            href: 'https://api.spotify.com/v1/artists/5K4W6rqBFWDnAN6FQUkS6x',
            id: '5K4W6rqBFWDnAN6FQUkS6x',
            name: 'Kanye West',
            type: 'artist',
            uri: 'spotify:artist:5K4W6rqBFWDnAN6FQUkS6x',
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/4STHEaNw4mPZ2tzheohgXB',
            },
            href: 'https://api.spotify.com/v1/artists/4STHEaNw4mPZ2tzheohgXB',
            id: '4STHEaNw4mPZ2tzheohgXB',
            name: 'Paul McCartney',
            type: 'artist',
            uri: 'spotify:artist:4STHEaNw4mPZ2tzheohgXB',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/7yBl4uFyJzH48Vy6tPieXL',
        },
        href: 'https://api.spotify.com/v1/albums/7yBl4uFyJzH48Vy6tPieXL',
        id: '7yBl4uFyJzH48Vy6tPieXL',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/ab67616d0000b27336a9ed72b45e54ff307641be',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/ab67616d00001e0236a9ed72b45e54ff307641be',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/ab67616d0000485136a9ed72b45e54ff307641be',
            width: 64,
          },
        ],
        name: 'FourFiveSeconds',
        release_date: '2015-01-24',
        release_date_precision: 'day',
        total_tracks: 1,
        type: 'album',
        uri: 'spotify:album:7yBl4uFyJzH48Vy6tPieXL',
      },
      {
        album_type: 'album',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5pKCCKE2ajJHZ9KAiaK11H',
            },
            href: 'https://api.spotify.com/v1/artists/5pKCCKE2ajJHZ9KAiaK11H',
            id: '5pKCCKE2ajJHZ9KAiaK11H',
            name: 'Rihanna',
            type: 'artist',
            uri: 'spotify:artist:5pKCCKE2ajJHZ9KAiaK11H',
          },
        ],
        available_markets: [
          'AD',
          'AU',
          'BG',
          'BR',
          'CA',
          'EE',
          'ES',
          'FI',
          'HK',
          'HU',
          'ID',
          'IN',
          'IS',
          'JP',
          'LI',
          'LT',
          'LV',
          'MC',
          'MX',
          'MY',
          'NO',
          'PH',
          'PT',
          'RO',
          'SG',
          'TH',
          'TW',
          'US',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/1ciAVKFdlpLi2eGDlXv6Bo',
        },
        href: 'https://api.spotify.com/v1/albums/1ciAVKFdlpLi2eGDlXv6Bo',
        id: '1ciAVKFdlpLi2eGDlXv6Bo',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/ab67616d0000b2737061b3d179b8b7363ffe1a50',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/ab67616d00001e027061b3d179b8b7363ffe1a50',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/ab67616d000048517061b3d179b8b7363ffe1a50',
            width: 64,
          },
        ],
        name: 'Unapologetic (Deluxe)',
        release_date: '2012-12-10',
        release_date_precision: 'day',
        total_tracks: 17,
        type: 'album',
        uri: 'spotify:album:1ciAVKFdlpLi2eGDlXv6Bo',
      },
      {
        album_type: 'album',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5pKCCKE2ajJHZ9KAiaK11H',
            },
            href: 'https://api.spotify.com/v1/artists/5pKCCKE2ajJHZ9KAiaK11H',
            id: '5pKCCKE2ajJHZ9KAiaK11H',
            name: 'Rihanna',
            type: 'artist',
            uri: 'spotify:artist:5pKCCKE2ajJHZ9KAiaK11H',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/2JdjS6jjOml7nt7Yjo0nnh',
        },
        href: 'https://api.spotify.com/v1/albums/2JdjS6jjOml7nt7Yjo0nnh',
        id: '2JdjS6jjOml7nt7Yjo0nnh',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/ab67616d0000b273d744a51e193d52170070062b',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/ab67616d00001e02d744a51e193d52170070062b',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/ab67616d00004851d744a51e193d52170070062b',
            width: 64,
          },
        ],
        name: 'A Girl Like Me',
        release_date: '2006-04-10',
        release_date_precision: 'day',
        total_tracks: 13,
        type: 'album',
        uri: 'spotify:album:2JdjS6jjOml7nt7Yjo0nnh',
      },
      {
        album_type: 'album',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5pKCCKE2ajJHZ9KAiaK11H',
            },
            href: 'https://api.spotify.com/v1/artists/5pKCCKE2ajJHZ9KAiaK11H',
            id: '5pKCCKE2ajJHZ9KAiaK11H',
            name: 'Rihanna',
            type: 'artist',
            uri: 'spotify:artist:5pKCCKE2ajJHZ9KAiaK11H',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/4FyGpObwABjn0o8Tdp7AZz',
        },
        href: 'https://api.spotify.com/v1/albums/4FyGpObwABjn0o8Tdp7AZz',
        id: '4FyGpObwABjn0o8Tdp7AZz',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/ab67616d0000b273b21609e1a2d7c1b7ba8efae2',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/ab67616d00001e02b21609e1a2d7c1b7ba8efae2',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/ab67616d00004851b21609e1a2d7c1b7ba8efae2',
            width: 64,
          },
        ],
        name: 'Music Of The Sun',
        release_date: '2005-08-29',
        release_date_precision: 'day',
        total_tracks: 13,
        type: 'album',
        uri: 'spotify:album:4FyGpObwABjn0o8Tdp7AZz',
      },
      {
        album_type: 'album',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5pKCCKE2ajJHZ9KAiaK11H',
            },
            href: 'https://api.spotify.com/v1/artists/5pKCCKE2ajJHZ9KAiaK11H',
            id: '5pKCCKE2ajJHZ9KAiaK11H',
            name: 'Rihanna',
            type: 'artist',
            uri: 'spotify:artist:5pKCCKE2ajJHZ9KAiaK11H',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/1Kw1bVd07oRqcjrcjQKC8T',
        },
        href: 'https://api.spotify.com/v1/albums/1Kw1bVd07oRqcjrcjQKC8T',
        id: '1Kw1bVd07oRqcjrcjQKC8T',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/ab67616d0000b2731c5eacf6965d328c2c795cef',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/ab67616d00001e021c5eacf6965d328c2c795cef',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/ab67616d000048511c5eacf6965d328c2c795cef',
            width: 64,
          },
        ],
        name: 'Talk That Talk',
        release_date: '2011-11-19',
        release_date_precision: 'day',
        total_tracks: 11,
        type: 'album',
        uri: 'spotify:album:1Kw1bVd07oRqcjrcjQKC8T',
      },
      {
        album_type: 'album',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5pKCCKE2ajJHZ9KAiaK11H',
            },
            href: 'https://api.spotify.com/v1/artists/5pKCCKE2ajJHZ9KAiaK11H',
            id: '5pKCCKE2ajJHZ9KAiaK11H',
            name: 'Rihanna',
            type: 'artist',
            uri: 'spotify:artist:5pKCCKE2ajJHZ9KAiaK11H',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/3sW7wD2qdMjs7KncaOoIJ5',
        },
        href: 'https://api.spotify.com/v1/albums/3sW7wD2qdMjs7KncaOoIJ5',
        id: '3sW7wD2qdMjs7KncaOoIJ5',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/ab67616d0000b273f70dcec206fbdbcc9816664a',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/ab67616d00001e02f70dcec206fbdbcc9816664a',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/ab67616d00004851f70dcec206fbdbcc9816664a',
            width: 64,
          },
        ],
        name: 'Talk That Talk (Deluxe)',
        release_date: '2012-07-18',
        release_date_precision: 'day',
        total_tracks: 14,
        type: 'album',
        uri: 'spotify:album:3sW7wD2qdMjs7KncaOoIJ5',
      },
      {
        album_type: 'single',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/2HPaUgqeutzr3jx5a9WyDV',
            },
            href: 'https://api.spotify.com/v1/artists/2HPaUgqeutzr3jx5a9WyDV',
            id: '2HPaUgqeutzr3jx5a9WyDV',
            name: 'PARTYNEXTDOOR',
            type: 'artist',
            uri: 'spotify:artist:2HPaUgqeutzr3jx5a9WyDV',
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5pKCCKE2ajJHZ9KAiaK11H',
            },
            href: 'https://api.spotify.com/v1/artists/5pKCCKE2ajJHZ9KAiaK11H',
            id: '5pKCCKE2ajJHZ9KAiaK11H',
            name: 'Rihanna',
            type: 'artist',
            uri: 'spotify:artist:5pKCCKE2ajJHZ9KAiaK11H',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/5Ku8vJclbcBKh3f3jwfNHy',
        },
        href: 'https://api.spotify.com/v1/albums/5Ku8vJclbcBKh3f3jwfNHy',
        id: '5Ku8vJclbcBKh3f3jwfNHy',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/ab67616d0000b2734c7a995ef70303e3c9e2ecb7',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/ab67616d00001e024c7a995ef70303e3c9e2ecb7',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/ab67616d000048514c7a995ef70303e3c9e2ecb7',
            width: 64,
          },
        ],
        name: 'BELIEVE IT',
        release_date: '2020-03-26',
        release_date_precision: 'day',
        total_tracks: 1,
        type: 'album',
        uri: 'spotify:album:5Ku8vJclbcBKh3f3jwfNHy',
      },
      {
        album_type: 'single',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/2HPaUgqeutzr3jx5a9WyDV',
            },
            href: 'https://api.spotify.com/v1/artists/2HPaUgqeutzr3jx5a9WyDV',
            id: '2HPaUgqeutzr3jx5a9WyDV',
            name: 'PARTYNEXTDOOR',
            type: 'artist',
            uri: 'spotify:artist:2HPaUgqeutzr3jx5a9WyDV',
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5pKCCKE2ajJHZ9KAiaK11H',
            },
            href: 'https://api.spotify.com/v1/artists/5pKCCKE2ajJHZ9KAiaK11H',
            id: '5pKCCKE2ajJHZ9KAiaK11H',
            name: 'Rihanna',
            type: 'artist',
            uri: 'spotify:artist:5pKCCKE2ajJHZ9KAiaK11H',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/44tafm4490xYqhfQKvMD4r',
        },
        href: 'https://api.spotify.com/v1/albums/44tafm4490xYqhfQKvMD4r',
        id: '44tafm4490xYqhfQKvMD4r',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/ab67616d0000b2730812033a08fd6058da3a0e57',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/ab67616d00001e020812033a08fd6058da3a0e57',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/ab67616d000048510812033a08fd6058da3a0e57',
            width: 64,
          },
        ],
        name: 'BELIEVE IT',
        release_date: '2020-03-26',
        release_date_precision: 'day',
        total_tracks: 1,
        type: 'album',
        uri: 'spotify:album:44tafm4490xYqhfQKvMD4r',
      },
      {
        album_type: 'album',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5pKCCKE2ajJHZ9KAiaK11H',
            },
            href: 'https://api.spotify.com/v1/artists/5pKCCKE2ajJHZ9KAiaK11H',
            id: '5pKCCKE2ajJHZ9KAiaK11H',
            name: 'Rihanna',
            type: 'artist',
            uri: 'spotify:artist:5pKCCKE2ajJHZ9KAiaK11H',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/48i37aZTC1prDr4EcpQeEa',
        },
        href: 'https://api.spotify.com/v1/albums/48i37aZTC1prDr4EcpQeEa',
        id: '48i37aZTC1prDr4EcpQeEa',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/ab67616d0000b2737b688587a6754481c53f6bb7',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/ab67616d00001e027b688587a6754481c53f6bb7',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/ab67616d000048517b688587a6754481c53f6bb7',
            width: 64,
          },
        ],
        name: 'ANTI',
        release_date: '2016-01-28',
        release_date_precision: 'day',
        total_tracks: 13,
        type: 'album',
        uri: 'spotify:album:48i37aZTC1prDr4EcpQeEa',
      },
      {
        album_type: 'single',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/4gzpq5DPGxSnKTe4SA8HAU',
            },
            href: 'https://api.spotify.com/v1/artists/4gzpq5DPGxSnKTe4SA8HAU',
            id: '4gzpq5DPGxSnKTe4SA8HAU',
            name: 'Coldplay',
            type: 'artist',
            uri: 'spotify:artist:4gzpq5DPGxSnKTe4SA8HAU',
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5pKCCKE2ajJHZ9KAiaK11H',
            },
            href: 'https://api.spotify.com/v1/artists/5pKCCKE2ajJHZ9KAiaK11H',
            id: '5pKCCKE2ajJHZ9KAiaK11H',
            name: 'Rihanna',
            type: 'artist',
            uri: 'spotify:artist:5pKCCKE2ajJHZ9KAiaK11H',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/3yddXawPNWK9qUDqB2UMY7',
        },
        href: 'https://api.spotify.com/v1/albums/3yddXawPNWK9qUDqB2UMY7',
        id: '3yddXawPNWK9qUDqB2UMY7',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/ab67616d0000b2730e56e43adfae6402ab272d17',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/ab67616d00001e020e56e43adfae6402ab272d17',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/ab67616d000048510e56e43adfae6402ab272d17',
            width: 64,
          },
        ],
        name: 'Princess of China',
        release_date: '2012-06-01',
        release_date_precision: 'day',
        total_tracks: 4,
        type: 'album',
        uri: 'spotify:album:3yddXawPNWK9qUDqB2UMY7',
      },
      {
        album_type: 'album',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5pKCCKE2ajJHZ9KAiaK11H',
            },
            href: 'https://api.spotify.com/v1/artists/5pKCCKE2ajJHZ9KAiaK11H',
            id: '5pKCCKE2ajJHZ9KAiaK11H',
            name: 'Rihanna',
            type: 'artist',
            uri: 'spotify:artist:5pKCCKE2ajJHZ9KAiaK11H',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/4XBfFj0WYyh5mBtU61EdyY',
        },
        href: 'https://api.spotify.com/v1/albums/4XBfFj0WYyh5mBtU61EdyY',
        id: '4XBfFj0WYyh5mBtU61EdyY',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/ab67616d0000b2736ede83cf8307a1d0174029ac',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/ab67616d00001e026ede83cf8307a1d0174029ac',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/ab67616d000048516ede83cf8307a1d0174029ac',
            width: 64,
          },
        ],
        name: 'Unapologetic',
        release_date: '2012-12-11',
        release_date_precision: 'day',
        total_tracks: 14,
        type: 'album',
        uri: 'spotify:album:4XBfFj0WYyh5mBtU61EdyY',
      },
      {
        album_type: 'single',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5pKCCKE2ajJHZ9KAiaK11H',
            },
            href: 'https://api.spotify.com/v1/artists/5pKCCKE2ajJHZ9KAiaK11H',
            id: '5pKCCKE2ajJHZ9KAiaK11H',
            name: 'Rihanna',
            type: 'artist',
            uri: 'spotify:artist:5pKCCKE2ajJHZ9KAiaK11H',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/1kv0MtCYndTXtkdzvGHkMx',
        },
        href: 'https://api.spotify.com/v1/albums/1kv0MtCYndTXtkdzvGHkMx',
        id: '1kv0MtCYndTXtkdzvGHkMx',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/ab67616d0000b273e5cba393eab0d67a715e7c39',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/ab67616d00001e02e5cba393eab0d67a715e7c39',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/ab67616d00004851e5cba393eab0d67a715e7c39',
            width: 64,
          },
        ],
        name: 'Sledgehammer (From The Motion Picture "Star Trek Beyond")',
        release_date: '2016-06-27',
        release_date_precision: 'day',
        total_tracks: 1,
        type: 'album',
        uri: 'spotify:album:1kv0MtCYndTXtkdzvGHkMx',
      },
    ],
    limit: 20,
    next:
      'https://api.spotify.com/v1/search?query=RIHANNA&type=album&offset=20&limit=20',
    offset: 0,
    previous: null,
    total: 1423,
  },
}
