export default {
  album_type: 'album',
  artists: [
    {
      external_urls: {
        spotify: 'https://open.spotify.com/artist/5pKCCKE2ajJHZ9KAiaK11H',
      },
      href: 'https://api.spotify.com/v1/artists/5pKCCKE2ajJHZ9KAiaK11H',
      id: '5pKCCKE2ajJHZ9KAiaK11H',
      name: 'Rihanna',
      type: 'artist',
      uri: 'spotify:artist:5pKCCKE2ajJHZ9KAiaK11H',
    },
  ],
  available_markets: [
    'AD',
    'AE',
    'AR',
    'AT',
    'AU',
    'BE',
    'BG',
    'BH',
    'BO',
    'BR',
    'CA',
    'CH',
    'CL',
    'CO',
    'CR',
    'CY',
    'CZ',
    'DE',
    'DK',
    'DO',
    'DZ',
    'EC',
    'EE',
    'EG',
    'ES',
    'FI',
    'FR',
    'GB',
    'GR',
    'GT',
    'HK',
    'HN',
    'HU',
    'ID',
    'IE',
    'IL',
    'IN',
    'IS',
    'IT',
    'JO',
    'JP',
    'KW',
    'LB',
    'LI',
    'LT',
    'LU',
    'LV',
    'MA',
    'MC',
    'MT',
    'MX',
    'MY',
    'NI',
    'NL',
    'NO',
    'NZ',
    'OM',
    'PA',
    'PE',
    'PH',
    'PL',
    'PS',
    'PT',
    'PY',
    'QA',
    'RO',
    'SA',
    'SE',
    'SG',
    'SK',
    'SV',
    'TH',
    'TN',
    'TR',
    'TW',
    'US',
    'UY',
    'VN',
    'ZA',
  ],
  copyrights: [
    {
      text:
        '© 2016 Westbury Road Entertainment. Distributed by Roc Nation Records',
      type: 'C',
    },
    {
      text:
        '℗ 2016 Westbury Road Entertainment. Distributed by Roc Nation Records',
      type: 'P',
    },
  ],
  external_ids: {
    upc: '00851365006554',
  },
  external_urls: {
    spotify: 'https://open.spotify.com/album/4UlGauD7ROb3YbVOFMgW5u',
  },
  genres: [],
  href: 'https://api.spotify.com/v1/albums/4UlGauD7ROb3YbVOFMgW5u',
  id: '4UlGauD7ROb3YbVOFMgW5u',
  images: [
    {
      height: 640,
      url: 'https://i.scdn.co/image/ab67616d0000b27333c6b920eabcf4c00d7a1093',
      width: 640,
    },
    {
      height: 300,
      url: 'https://i.scdn.co/image/ab67616d00001e0233c6b920eabcf4c00d7a1093',
      width: 300,
    },
    {
      height: 64,
      url: 'https://i.scdn.co/image/ab67616d0000485133c6b920eabcf4c00d7a1093',
      width: 64,
    },
  ],
  label: 'Roc Nation / Rihanna',
  name: 'ANTI (Deluxe)',
  popularity: 80,
  release_date: '2016-01-28',
  release_date_precision: 'day',
  total_tracks: 16,
  //here
  tracks: {
    href:
      'https://api.spotify.com/v1/albums/4UlGauD7ROb3YbVOFMgW5u/tracks?offset=0&limit=50',
    items: [
      {
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5pKCCKE2ajJHZ9KAiaK11H',
            },
            href: 'https://api.spotify.com/v1/artists/5pKCCKE2ajJHZ9KAiaK11H',
            id: '5pKCCKE2ajJHZ9KAiaK11H',
            name: 'Rihanna',
            type: 'artist',
            uri: 'spotify:artist:5pKCCKE2ajJHZ9KAiaK11H',
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/7tYKF4w9nC0nq9CsPZTHyP',
            },
            href: 'https://api.spotify.com/v1/artists/7tYKF4w9nC0nq9CsPZTHyP',
            id: '7tYKF4w9nC0nq9CsPZTHyP',
            name: 'SZA',
            type: 'artist',
            uri: 'spotify:artist:7tYKF4w9nC0nq9CsPZTHyP',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        disc_number: 1,
        duration_ms: 161066,
        explicit: true,
        external_urls: {
          spotify: 'https://open.spotify.com/track/6t90Z9XkdsHD8xMxro6KRP',
        },
        href: 'https://api.spotify.com/v1/tracks/6t90Z9XkdsHD8xMxro6KRP',
        id: '6t90Z9XkdsHD8xMxro6KRP',
        is_local: false,
        name: 'Consideration',
        preview_url:
          'https://p.scdn.co/mp3-preview/5ed5f5f05f603c7ef1ad5f03abf6d7b8eeafd03e?cid=95555d82a874400ab026efab926d00ae',
        track_number: 1,
        type: 'track',
        uri: 'spotify:track:6t90Z9XkdsHD8xMxro6KRP',
      },
      {
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5pKCCKE2ajJHZ9KAiaK11H',
            },
            href: 'https://api.spotify.com/v1/artists/5pKCCKE2ajJHZ9KAiaK11H',
            id: '5pKCCKE2ajJHZ9KAiaK11H',
            name: 'Rihanna',
            type: 'artist',
            uri: 'spotify:artist:5pKCCKE2ajJHZ9KAiaK11H',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        disc_number: 1,
        duration_ms: 72080,
        explicit: true,
        external_urls: {
          spotify: 'https://open.spotify.com/track/6K4Co1NQyOnoFEJMkZHkln',
        },
        href: 'https://api.spotify.com/v1/tracks/6K4Co1NQyOnoFEJMkZHkln',
        id: '6K4Co1NQyOnoFEJMkZHkln',
        is_local: false,
        name: 'James Joint',
        preview_url:
          'https://p.scdn.co/mp3-preview/8fc2a6771f56a60683979bd876bc6b73f25052a1?cid=95555d82a874400ab026efab926d00ae',
        track_number: 2,
        type: 'track',
        uri: 'spotify:track:6K4Co1NQyOnoFEJMkZHkln',
      },
      {
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5pKCCKE2ajJHZ9KAiaK11H',
            },
            href: 'https://api.spotify.com/v1/artists/5pKCCKE2ajJHZ9KAiaK11H',
            id: '5pKCCKE2ajJHZ9KAiaK11H',
            name: 'Rihanna',
            type: 'artist',
            uri: 'spotify:artist:5pKCCKE2ajJHZ9KAiaK11H',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        disc_number: 1,
        duration_ms: 253080,
        explicit: true,
        external_urls: {
          spotify: 'https://open.spotify.com/track/0UHB9METy4VCXNgkcGqHqS',
        },
        href: 'https://api.spotify.com/v1/tracks/0UHB9METy4VCXNgkcGqHqS',
        id: '0UHB9METy4VCXNgkcGqHqS',
        is_local: false,
        name: 'Kiss It Better',
        preview_url:
          'https://p.scdn.co/mp3-preview/5857fe6cdb7597f6da72c3951696086c042045ed?cid=95555d82a874400ab026efab926d00ae',
        track_number: 3,
        type: 'track',
        uri: 'spotify:track:0UHB9METy4VCXNgkcGqHqS',
      },
      {
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5pKCCKE2ajJHZ9KAiaK11H',
            },
            href: 'https://api.spotify.com/v1/artists/5pKCCKE2ajJHZ9KAiaK11H',
            id: '5pKCCKE2ajJHZ9KAiaK11H',
            name: 'Rihanna',
            type: 'artist',
            uri: 'spotify:artist:5pKCCKE2ajJHZ9KAiaK11H',
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/3TVXtAsR1Inumwj472S9r4',
            },
            href: 'https://api.spotify.com/v1/artists/3TVXtAsR1Inumwj472S9r4',
            id: '3TVXtAsR1Inumwj472S9r4',
            name: 'Drake',
            type: 'artist',
            uri: 'spotify:artist:3TVXtAsR1Inumwj472S9r4',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        disc_number: 1,
        duration_ms: 219320,
        explicit: true,
        external_urls: {
          spotify: 'https://open.spotify.com/track/72TFWvU3wUYdUuxejTTIzt',
        },
        href: 'https://api.spotify.com/v1/tracks/72TFWvU3wUYdUuxejTTIzt',
        id: '72TFWvU3wUYdUuxejTTIzt',
        is_local: false,
        name: 'Work',
        preview_url:
          'https://p.scdn.co/mp3-preview/528dc6d0ff5089b13b86cd8b0c921910b823bdd1?cid=95555d82a874400ab026efab926d00ae',
        track_number: 4,
        type: 'track',
        uri: 'spotify:track:72TFWvU3wUYdUuxejTTIzt',
      },
      {
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5pKCCKE2ajJHZ9KAiaK11H',
            },
            href: 'https://api.spotify.com/v1/artists/5pKCCKE2ajJHZ9KAiaK11H',
            id: '5pKCCKE2ajJHZ9KAiaK11H',
            name: 'Rihanna',
            type: 'artist',
            uri: 'spotify:artist:5pKCCKE2ajJHZ9KAiaK11H',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        disc_number: 1,
        duration_ms: 186466,
        explicit: false,
        external_urls: {
          spotify: 'https://open.spotify.com/track/4mCf3vQf7z0Yseo0RxAi3V',
        },
        href: 'https://api.spotify.com/v1/tracks/4mCf3vQf7z0Yseo0RxAi3V',
        id: '4mCf3vQf7z0Yseo0RxAi3V',
        is_local: false,
        name: 'Desperado',
        preview_url:
          'https://p.scdn.co/mp3-preview/bbae6c827b16892a5eec6ff08fab5c86baff3e66?cid=95555d82a874400ab026efab926d00ae',
        track_number: 5,
        type: 'track',
        uri: 'spotify:track:4mCf3vQf7z0Yseo0RxAi3V',
      },
      {
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5pKCCKE2ajJHZ9KAiaK11H',
            },
            href: 'https://api.spotify.com/v1/artists/5pKCCKE2ajJHZ9KAiaK11H',
            id: '5pKCCKE2ajJHZ9KAiaK11H',
            name: 'Rihanna',
            type: 'artist',
            uri: 'spotify:artist:5pKCCKE2ajJHZ9KAiaK11H',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        disc_number: 1,
        duration_ms: 235586,
        explicit: true,
        external_urls: {
          spotify: 'https://open.spotify.com/track/3HQcsqRjRdruUjkbDSgmVF',
        },
        href: 'https://api.spotify.com/v1/tracks/3HQcsqRjRdruUjkbDSgmVF',
        id: '3HQcsqRjRdruUjkbDSgmVF',
        is_local: false,
        name: 'Woo',
        preview_url:
          'https://p.scdn.co/mp3-preview/dc0bfa6789cb0755b1ed8150d9bdec8763b7d857?cid=95555d82a874400ab026efab926d00ae',
        track_number: 6,
        type: 'track',
        uri: 'spotify:track:3HQcsqRjRdruUjkbDSgmVF',
      },
      {
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5pKCCKE2ajJHZ9KAiaK11H',
            },
            href: 'https://api.spotify.com/v1/artists/5pKCCKE2ajJHZ9KAiaK11H',
            id: '5pKCCKE2ajJHZ9KAiaK11H',
            name: 'Rihanna',
            type: 'artist',
            uri: 'spotify:artist:5pKCCKE2ajJHZ9KAiaK11H',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        disc_number: 1,
        duration_ms: 191600,
        explicit: true,
        external_urls: {
          spotify: 'https://open.spotify.com/track/4pAl7FkDMNBsjykPXo91B3',
        },
        href: 'https://api.spotify.com/v1/tracks/4pAl7FkDMNBsjykPXo91B3',
        id: '4pAl7FkDMNBsjykPXo91B3',
        is_local: false,
        name: 'Needed Me',
        preview_url:
          'https://p.scdn.co/mp3-preview/417b7df9f259ca410e9b42c194424b5c41189897?cid=95555d82a874400ab026efab926d00ae',
        track_number: 7,
        type: 'track',
        uri: 'spotify:track:4pAl7FkDMNBsjykPXo91B3',
      },
      {
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5pKCCKE2ajJHZ9KAiaK11H',
            },
            href: 'https://api.spotify.com/v1/artists/5pKCCKE2ajJHZ9KAiaK11H',
            id: '5pKCCKE2ajJHZ9KAiaK11H',
            name: 'Rihanna',
            type: 'artist',
            uri: 'spotify:artist:5pKCCKE2ajJHZ9KAiaK11H',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        disc_number: 1,
        duration_ms: 133080,
        explicit: true,
        external_urls: {
          spotify: 'https://open.spotify.com/track/7eDYNlBwRMeFOZHOZ95dZ1',
        },
        href: 'https://api.spotify.com/v1/tracks/7eDYNlBwRMeFOZHOZ95dZ1',
        id: '7eDYNlBwRMeFOZHOZ95dZ1',
        is_local: false,
        name: 'Yeah, I Said It',
        preview_url:
          'https://p.scdn.co/mp3-preview/828382a1a8c7b287d18162bfe46369a889d1156d?cid=95555d82a874400ab026efab926d00ae',
        track_number: 8,
        type: 'track',
        uri: 'spotify:track:7eDYNlBwRMeFOZHOZ95dZ1',
      },
      {
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5pKCCKE2ajJHZ9KAiaK11H',
            },
            href: 'https://api.spotify.com/v1/artists/5pKCCKE2ajJHZ9KAiaK11H',
            id: '5pKCCKE2ajJHZ9KAiaK11H',
            name: 'Rihanna',
            type: 'artist',
            uri: 'spotify:artist:5pKCCKE2ajJHZ9KAiaK11H',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        disc_number: 1,
        duration_ms: 397093,
        explicit: false,
        external_urls: {
          spotify: 'https://open.spotify.com/track/6RtzmszGXs32TRhv5zTKNM',
        },
        href: 'https://api.spotify.com/v1/tracks/6RtzmszGXs32TRhv5zTKNM',
        id: '6RtzmszGXs32TRhv5zTKNM',
        is_local: false,
        name: 'Same Ol’ Mistakes',
        preview_url:
          'https://p.scdn.co/mp3-preview/1bb3f5391fc2cec62ea39a8aa79d6309d4b6a919?cid=95555d82a874400ab026efab926d00ae',
        track_number: 9,
        type: 'track',
        uri: 'spotify:track:6RtzmszGXs32TRhv5zTKNM',
      },
      {
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5pKCCKE2ajJHZ9KAiaK11H',
            },
            href: 'https://api.spotify.com/v1/artists/5pKCCKE2ajJHZ9KAiaK11H',
            id: '5pKCCKE2ajJHZ9KAiaK11H',
            name: 'Rihanna',
            type: 'artist',
            uri: 'spotify:artist:5pKCCKE2ajJHZ9KAiaK11H',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        disc_number: 1,
        duration_ms: 202506,
        explicit: false,
        external_urls: {
          spotify: 'https://open.spotify.com/track/7Jd5LgnSRQElW6FsTWVPzE',
        },
        href: 'https://api.spotify.com/v1/tracks/7Jd5LgnSRQElW6FsTWVPzE',
        id: '7Jd5LgnSRQElW6FsTWVPzE',
        is_local: false,
        name: 'Never Ending',
        preview_url:
          'https://p.scdn.co/mp3-preview/1599997bfeac0eb33480ce636042a2fb2f3d9860?cid=95555d82a874400ab026efab926d00ae',
        track_number: 10,
        type: 'track',
        uri: 'spotify:track:7Jd5LgnSRQElW6FsTWVPzE',
      },
      {
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5pKCCKE2ajJHZ9KAiaK11H',
            },
            href: 'https://api.spotify.com/v1/artists/5pKCCKE2ajJHZ9KAiaK11H',
            id: '5pKCCKE2ajJHZ9KAiaK11H',
            name: 'Rihanna',
            type: 'artist',
            uri: 'spotify:artist:5pKCCKE2ajJHZ9KAiaK11H',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        disc_number: 1,
        duration_ms: 224000,
        explicit: true,
        external_urls: {
          spotify: 'https://open.spotify.com/track/5oO3drDxtziYU2H1X23ZIp',
        },
        href: 'https://api.spotify.com/v1/tracks/5oO3drDxtziYU2H1X23ZIp',
        id: '5oO3drDxtziYU2H1X23ZIp',
        is_local: false,
        name: 'Love On The Brain',
        preview_url:
          'https://p.scdn.co/mp3-preview/9440a1af919c309386b9692c42210dd53c2ac9b5?cid=95555d82a874400ab026efab926d00ae',
        track_number: 11,
        type: 'track',
        uri: 'spotify:track:5oO3drDxtziYU2H1X23ZIp',
      },
      {
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5pKCCKE2ajJHZ9KAiaK11H',
            },
            href: 'https://api.spotify.com/v1/artists/5pKCCKE2ajJHZ9KAiaK11H',
            id: '5pKCCKE2ajJHZ9KAiaK11H',
            name: 'Rihanna',
            type: 'artist',
            uri: 'spotify:artist:5pKCCKE2ajJHZ9KAiaK11H',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        disc_number: 1,
        duration_ms: 120626,
        explicit: true,
        external_urls: {
          spotify: 'https://open.spotify.com/track/1KnJwhZU3DIBe54Q4HPpIl',
        },
        href: 'https://api.spotify.com/v1/tracks/1KnJwhZU3DIBe54Q4HPpIl',
        id: '1KnJwhZU3DIBe54Q4HPpIl',
        is_local: false,
        name: 'Higher',
        preview_url:
          'https://p.scdn.co/mp3-preview/6b7e55c2333520e0da1588aa8e76e24d85ff9760?cid=95555d82a874400ab026efab926d00ae',
        track_number: 12,
        type: 'track',
        uri: 'spotify:track:1KnJwhZU3DIBe54Q4HPpIl',
      },
      {
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5pKCCKE2ajJHZ9KAiaK11H',
            },
            href: 'https://api.spotify.com/v1/artists/5pKCCKE2ajJHZ9KAiaK11H',
            id: '5pKCCKE2ajJHZ9KAiaK11H',
            name: 'Rihanna',
            type: 'artist',
            uri: 'spotify:artist:5pKCCKE2ajJHZ9KAiaK11H',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        disc_number: 1,
        duration_ms: 223213,
        explicit: false,
        external_urls: {
          spotify: 'https://open.spotify.com/track/6D2tzc8kRnZb7P1lNwMBLH',
        },
        href: 'https://api.spotify.com/v1/tracks/6D2tzc8kRnZb7P1lNwMBLH',
        id: '6D2tzc8kRnZb7P1lNwMBLH',
        is_local: false,
        name: 'Close To You',
        preview_url:
          'https://p.scdn.co/mp3-preview/81e150062456011c4a0d3f72625b988762437f97?cid=95555d82a874400ab026efab926d00ae',
        track_number: 13,
        type: 'track',
        uri: 'spotify:track:6D2tzc8kRnZb7P1lNwMBLH',
      },
      {
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5pKCCKE2ajJHZ9KAiaK11H',
            },
            href: 'https://api.spotify.com/v1/artists/5pKCCKE2ajJHZ9KAiaK11H',
            id: '5pKCCKE2ajJHZ9KAiaK11H',
            name: 'Rihanna',
            type: 'artist',
            uri: 'spotify:artist:5pKCCKE2ajJHZ9KAiaK11H',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        disc_number: 1,
        duration_ms: 88493,
        explicit: false,
        external_urls: {
          spotify: 'https://open.spotify.com/track/5LJz7kmFhLqB53tmVWxig5',
        },
        href: 'https://api.spotify.com/v1/tracks/5LJz7kmFhLqB53tmVWxig5',
        id: '5LJz7kmFhLqB53tmVWxig5',
        is_local: false,
        name: 'Goodnight Gotham',
        preview_url:
          'https://p.scdn.co/mp3-preview/5215e52a2d3cfb13a0d94b73064dda5c89aaf504?cid=95555d82a874400ab026efab926d00ae',
        track_number: 14,
        type: 'track',
        uri: 'spotify:track:5LJz7kmFhLqB53tmVWxig5',
      },
      {
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5pKCCKE2ajJHZ9KAiaK11H',
            },
            href: 'https://api.spotify.com/v1/artists/5pKCCKE2ajJHZ9KAiaK11H',
            id: '5pKCCKE2ajJHZ9KAiaK11H',
            name: 'Rihanna',
            type: 'artist',
            uri: 'spotify:artist:5pKCCKE2ajJHZ9KAiaK11H',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        disc_number: 1,
        duration_ms: 144226,
        explicit: true,
        external_urls: {
          spotify: 'https://open.spotify.com/track/4UTizOdGljPIIbXtoXycAd',
        },
        href: 'https://api.spotify.com/v1/tracks/4UTizOdGljPIIbXtoXycAd',
        id: '4UTizOdGljPIIbXtoXycAd',
        is_local: false,
        name: 'Pose',
        preview_url:
          'https://p.scdn.co/mp3-preview/97f778cb99ab50c4a1d4c806da244d547c12899c?cid=95555d82a874400ab026efab926d00ae',
        track_number: 15,
        type: 'track',
        uri: 'spotify:track:4UTizOdGljPIIbXtoXycAd',
      },
      {
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5pKCCKE2ajJHZ9KAiaK11H',
            },
            href: 'https://api.spotify.com/v1/artists/5pKCCKE2ajJHZ9KAiaK11H',
            id: '5pKCCKE2ajJHZ9KAiaK11H',
            name: 'Rihanna',
            type: 'artist',
            uri: 'spotify:artist:5pKCCKE2ajJHZ9KAiaK11H',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        disc_number: 1,
        duration_ms: 206400,
        explicit: true,
        external_urls: {
          spotify: 'https://open.spotify.com/track/7BiELrM90hRxpozaIXbsLw',
        },
        href: 'https://api.spotify.com/v1/tracks/7BiELrM90hRxpozaIXbsLw',
        id: '7BiELrM90hRxpozaIXbsLw',
        is_local: false,
        name: 'Sex With Me',
        preview_url:
          'https://p.scdn.co/mp3-preview/88e0409d47fedf039b94c30ac318b2448bfc4c32?cid=95555d82a874400ab026efab926d00ae',
        track_number: 16,
        type: 'track',
        uri: 'spotify:track:7BiELrM90hRxpozaIXbsLw',
      },
    ],
    limit: 50,
    next: null,
    offset: 0,
    previous: null,
    total: 16,
  },
  type: 'album',
  uri: 'spotify:album:4UlGauD7ROb3YbVOFMgW5u',
}
