import MODULE from './module'

export default {
  UPDATE_VOLUME: `@${MODULE}/UPDATE_VOLUME`,
  PLAY_SONG: `@${MODULE}/PLAY_SONG`,
  STOP_SONG: `@${MODULE}/STOP_SONG`,
  PAUSE_SONG: `@${MODULE}/PAUSE_SONG`,
  RESUME_SONG: `@${MODULE}/RESUME_SONG`,
  INCREASE_SONG_TIME: `@${MODULE}/INCREASE_SONG_TIME`,
}
