import MODULE from './module'

export default {
  GET_TOKEN: `@${MODULE}/GET_TOKEN_REQUEST`,
  GET_TOKEN_SUCCESS: `@${MODULE}/GET_TOKEN_SUCCESS`,
  GET_TOKEN_ERROR: `@${MODULE}/GET_TOKEN_ERROR`,
  REQUEST_REFRESH_TOKEN: `@${MODULE}/REQUEST_REFRESH_TOKEN`,
  GET_REFRESH_TOKEN: `@${MODULE}/GET_REFRESH_TOKEN_REQUEST`,
}
