import MODULE from './module'

export default {
  SEARCH_SONGS: `@${MODULE}/SEARCH_SONGS`,
  SEARCH_SONGS_SUCCESS: `@${MODULE}/SEARCH_SONGS_SUCCESS`,
  SEARCH_SONGS_ERROR: `@${MODULE}/SEARCH_SONGS_ERROR`,
  CLEAR_SONGS: `@${MODULE}/CLEAR_SONGS`,
  SET_ALBUM: `@${MODULE}/SET_ALBUM`,
  CLEAR_ALBUM: `@${MODULE}/CLEAR_ALBUM`,
}
